FROM ubuntu:20.04
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

## Install npm to run front-end
RUN apt-get update && \
	apt-get install -y npm
COPY ./angular4-frontend/ /home/angular4-frontend
WORKDIR /home/angular4-frontend/
RUN npm install

## Install third-party tool to run angular app as daemon
RUN npm install pm2 -g

ENTRYPOINT ["pm2 --name demo start npm -- start"]

EXPOSE 4200