FROM ubuntu:20.04
	
## Install Java 8
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update && \
	apt-get install -y openjdk-8-jdk
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export JAVA_HOME

## Install maven
RUN apt-get update && \
	apt-get install -y maven
ENV MAVEN_HOME=/opt/maven
RUN export MAVEN_HOME

## Copy backend to container
COPY ../spring-boot-backend /home/spring-boot-backend

## Package the backend 
WORKDIR /home/spring-boot-backend
RUN mvn package

## Run jar file 
ENTRYPOINT ["java -jar /home/spring-boot-backend/target/todoapp-0.0.1-SNAPSHOT.jar"]
EXPOSE 8081
